{% set name = "phylorank" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 54c7ef9a47734b86676978e41859a37354540dfe5b41eb73e23ea57dc8de8174

build:

  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy
    - matplotlib-base
    - jinja2 >=2.7.3
    - dendropy >=4.1.0
    - biolib >=0.1.0
    - scipy
    - mpld3 >=0.2

test:
  imports:
    - phylorank
    - phylorank.plot
  commands:
    - phylorank -h

about:
  home: https://github.com/dparks1134/PhyloRank
  license: GNU General Public v3 (GPLv3)
  license_family: GPL3
  license_file: LICENSE.txt
  summary: 'PhyloRank provides functionality for calculating the relative evolutionary divergence (RED) of taxa in a tree and for finding the best placement of taxonomic labels in a tree.'
